# Site settings
title: lusongcai
url: "https://lusongcai.github.io"    # the protocol and hostname of your site, eg. `http://zhaoyuxiang.cn/blog`
baseurl: "/bohu-jekyll-theme" # the prefix of your site uri, eg. `/bohu-jekyll-theme` or just one slash `/`
#timezone: Asia/Shanghai
description: 个人学前端
# Your information
email: songcai01@163.com
author: 卢松才 #yourname #天道总司
place: 深圳 #杭州
domain: android #互联网
company: 无#Jeeyoo
position: 无 #Technical Support
school: 无 #浙江科技学院
major: 无 #测控技术与仪器
resume: "https//lusongcai.github.io"
profile: goog goog study,day day up. #yourmotto #聪明在于勤奋，天才在于积累。
weibo_username:  _卢松才
github_username:  lusongcai

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
# get one: https://disqus.com/admin/signup/
# duoshuo_shortname: clark-zhao  
# get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 2
paginate_path: "/page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
